-- primary key op de tabel zetten
ALTER TABLE CLEANSED.Orders ADD CONSTRAINT
	PK_orders PRIMARY KEY CLUSTERED
	(
		[OrderID]
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE CLEANSED.Orders SET (LOCK_ESCALATION = TABLE)
GO