-- primary key op de tabel zetten
ALTER TABLE CLEANSED.OrderLines ADD CONSTRAINT
	PK_orders PRIMARY KEY CLUSTERED
	(
		[OrderLineID]
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE CLEANSED.OrderLines SET (LOCK_ESCALATION = TABLE)
GO