-- primary key op de tabel zetten
ALTER TABLE CLEANSED.Persons ADD CONSTRAINT
	PK_persons PRIMARY KEY CLUSTERED
	(
		[PersonID]
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE CLEANSED.Persons SET (LOCK_ESCALATION = TABLE)
GO