-- primary key op de tabel zetten
ALTER TABLE CLEANSED.Customers ADD CONSTRAINT
	PK_customers PRIMARY KEY CLUSTERED
	(
		[CustomerID]
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE CLEANSED.Customers SET (LOCK_ESCALATION = TABLE)
GO