-- primary key op de tabel zetten
ALTER TABLE CLEANSED.Suppliers ADD CONSTRAINT
	PK_suppliers PRIMARY KEY CLUSTERED
	(
		[SupplierID]
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE CLEANSED.Suppliers SET (LOCK_ESCALATION = TABLE)
GO