-- primary key op de tabel zetten
ALTER TABLE CLEANSED.StateProvinces ADD CONSTRAINT
	PK_stateProvinces PRIMARY KEY CLUSTERED
	(
		[StateProvinceID]
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE CLEANSED.StateProvinces SET (LOCK_ESCALATION = TABLE)
GO