-- primary key op de tabel zetten
ALTER TABLE CLEANSED.SupplierCategories ADD CONSTRAINT
	PK_supplierCategories PRIMARY KEY CLUSTERED
	(
		[SupplierCategoryID]
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE CLEANSED.SupplierCategories SET (LOCK_ESCALATION = TABLE)
GO